version: "2"
services:
    nginx:
      build:
          context: ./dockerfiles/nginx
      networks:
          - default
      links:
       - rest:rest
       - prov:prov
      ports:
       - "8000:8000"
    rest:
      build:
          context: ./dockerfiles/rest
      networks:
          - default
      links:
       - postgres_db:db
      volumes:
       - ./workspace/gather-rest:/code
      command: [bash, /code/setup_rest.sh]
    prov:
      build:
          context: ./dockerfiles/prov
      networks:
          - default
      links:
       - rest:rest
       - postgres_db:db
      volumes:
       - ./workspace/gather-prov:/code
      command: [bash, /code/setup_prov.sh]
    test:
      build:
          context: ./dockerfiles/test
      networks:
          - default
      links:
       - rest:rest
       - prov:prov
       - nginx:nginx
      volumes:
       - ./workspace/gather-tests:/code
      command: [bash, /code/setup_test.sh]
    postgres_db:
      image:  postgres
      networks:
          - default
networks:
    default:
        driver: bridge
